import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type CopyType } from '../taxonomies/copyType';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Free Text
 * Id: bcebf480-5936-4145-847c-be9eface8be8
 * Codename: free_text
 */
export type FreeText = IContentItem<{
    /**
     * Body Copy (rich_text)
     * Required: true
     * Id: c565dd05-c3b1-46c3-9194-67013409dd70
     * Codename: body_copy
     */
    bodyCopy: Elements.RichTextElement;

    /**
     * Copy Type (taxonomy)
     * Required: false
     * Id: 2b2bc541-0f77-47cd-8847-479ee9b73879
     * Codename: copy_type
     */
    copyType: Elements.TaxonomyElement<CopyType>;

    /**
     * Title (text)
     * Required: true
     * Id: e1097da0-4d32-4f2b-b9d7-f667fbf80474
     * Codename: title
     */
    title: Elements.TextElement;
}>;
