/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Copy Type
 * Id: 11adcc79-b042-4de5-9529-4b0e711c7b28
 * Codename: specialist_wording
 */
export type CopyType =
    | 'blog'
    | 'brochure_pages'
    | 'caveat'
    | 'editorial'
    | 'intro'
    | 'letter'
    | 'section_intros'
    | 'small_print';
