/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Tour Type
 * Id: 6f59296a-e360-4799-9d69-df6c577ec9f3
 * Codename: tour_type
 */
export type TourType =
    | 'astro'
    | 'channel_islands'
    | 'classic'
    | 'cruise'
    | 'eu'
    | 'events'
    | 'family_fun'
    | 'festive'
    | 'heritage'
    | 'inbound'
    | 'ireland'
    | 'london'
    | 'sports'
    | 'supervalue'
    | 'winter_sun';
