/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const contentTypes = {
    /**
     * Excursion
     */
    excursion: {
        codename: 'excursion',
        id: '08958491-9d29-4b76-bf62-b6b7d27c99b4',
        externalId: undefined,
        name: 'Excursion',
        elements: {
            /**
             * Description (rich_text)
             */
            description: {
                codename: 'description',
                id: '03a718d8-074c-47a2-b300-ae1c73c86c21',
                externalId: undefined,
                name: 'Description',
                required: false,
                type: 'rich_text'
            },

            /**
             * Destination (rich_text)
             */
            destination: {
                codename: 'destination',
                id: '9bb18daf-9163-42e8-bcad-1470de98b98a',
                externalId: undefined,
                name: 'Destination',
                required: false,
                type: 'rich_text'
            },

            /**
             * Duration  Half Day Full Day  (text)
             */
            duration__half_day_full_day_: {
                codename: 'duration__half_day_full_day_',
                id: 'ccbb2b3d-9b6a-4cc7-8a9d-77f85cef3400',
                externalId: undefined,
                name: 'Duration (Half Day/Full Day)',
                required: false,
                type: 'text'
            },

            /**
             * Price in   pp (number)
             */
            price_in___pp: {
                codename: 'price_in___pp',
                id: '3d5844b1-ecba-43d4-9408-ca8e5d711949',
                externalId: undefined,
                name: 'Price in £ pp',
                required: false,
                type: 'number'
            }
        }
    },

    /**
     * Export Module
     */
    export_module: {
        codename: 'export_module',
        id: '446719ae-3c3b-48b0-b824-000594043d43',
        externalId: undefined,
        name: 'Export Module',
        elements: {
            /**
             * Export to CSV (custom)
             */
            export_to_csv: {
                codename: 'export_to_csv',
                id: '0634cc12-0ef4-4b03-874c-f267aec175ac',
                externalId: undefined,
                name: 'Export to CSV',
                required: false,
                type: 'custom'
            },

            /**
             * Tours to export (modular_content)
             */
            tours_to_export: {
                codename: 'tours_to_export',
                id: 'bcfc6a84-beab-471a-8e03-c9e4e5d924ff',
                externalId: undefined,
                name: 'Tours to export',
                required: false,
                type: 'modular_content'
            }
        }
    },

    /**
     * Free Text
     */
    free_text: {
        codename: 'free_text',
        id: 'bcebf480-5936-4145-847c-be9eface8be8',
        externalId: undefined,
        name: 'Free Text',
        elements: {
            /**
             * Body Copy (rich_text)
             */
            body_copy: {
                codename: 'body_copy',
                id: 'c565dd05-c3b1-46c3-9194-67013409dd70',
                externalId: undefined,
                name: 'Body Copy',
                required: true,
                type: 'rich_text'
            },

            /**
             * Copy Type (taxonomy)
             */
            copy_type: {
                codename: 'copy_type',
                id: '2b2bc541-0f77-47cd-8847-479ee9b73879',
                externalId: undefined,
                name: 'Copy Type',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'e1097da0-4d32-4f2b-b9d7-f667fbf80474',
                externalId: undefined,
                name: 'Title',
                required: true,
                type: 'text'
            }
        }
    },

    /**
     * Hotel
     */
    hotel: {
        codename: 'hotel',
        id: 'd01c04c4-cc44-49df-b0c1-2abf703b0360',
        externalId: undefined,
        name: 'Hotel',
        elements: {
            /**
             * Accessibility Information (text)
             */
            accessibility_information: {
                codename: 'accessibility_information',
                id: '9a90a892-7e67-40c4-bfc6-cd6ac4d60b63',
                externalId: undefined,
                name: 'Accessibility Information',
                required: false,
                type: 'text'
            },

            /**
             * Description (rich_text)
             */
            description: {
                codename: 'description',
                id: 'ada93ab5-a20f-43af-9e29-5d7bfac08d15',
                externalId: undefined,
                name: 'Description',
                required: false,
                type: 'rich_text'
            },

            /**
             * Name (rich_text)
             */
            name: {
                codename: 'name',
                id: 'e1b01826-4674-4d67-a058-a522edc97a28',
                externalId: undefined,
                name: 'Name',
                required: false,
                type: 'rich_text'
            },

            /**
             * Rating (text)
             */
            rating: {
                codename: 'rating',
                id: '6d703ef0-308e-4356-b406-8ad46d39333d',
                externalId: undefined,
                name: 'Rating',
                required: false,
                type: 'text'
            },

            /**
             * Untitled multiple choice (multiple_choice)
             */
            untitled_multiple_choice: {
                codename: 'untitled_multiple_choice',
                id: 'f0968608-36c5-4a48-9f8d-91041a6bd4b0',
                externalId: undefined,
                name: 'Untitled multiple choice',
                required: false,
                type: 'multiple_choice',
                options: {
                    lift_to_all_floors: {
                        name: 'Lift to all Floors',
                        id: 'a02b0845-41f9-4bfe-be18-f84c83a7abef',
                        codename: 'lift_to_all_floors',
                        externalId: undefined
                    },
                    walk_in_showers: {
                        name: 'Walk in Showers',
                        id: '585cae31-e5fb-4754-be80-f9da899b9ab6',
                        codename: 'walk_in_showers',
                        externalId: undefined
                    },
                    steps_at_entrance: {
                        name: 'Steps at entrance',
                        id: '5f63c274-5340-403b-b52b-2b743e8c102b',
                        codename: 'steps_at_entrance',
                        externalId: undefined
                    }
                }
            }
        }
    },

    /**
     * Tour
     */
    tour: {
        codename: 'tour',
        id: '6a42abf2-4651-4cbb-bf59-e0995d442de8',
        externalId: undefined,
        name: 'Tour',
        elements: {
            /**
             * BPM Includes (rich_text)
             */
            bpm_includes: {
                codename: 'bpm_includes',
                id: '30142482-8471-4743-a6bf-d409db91dd8b',
                externalId: undefined,
                name: 'BPM Includes',
                required: false,
                type: 'rich_text'
            },

            /**
             * Export Tour (custom)
             */
            export_tour: {
                codename: 'export_tour',
                id: '187c79ff-8347-4ce8-950a-ca3b5facb689',
                externalId: undefined,
                name: 'Export Tour',
                required: false,
                type: 'custom'
            },

            /**
             * Hotel s  (modular_content)
             */
            hotel_s_: {
                codename: 'hotel_s_',
                id: '3d8c6dac-c711-40ef-82ff-33fe75dbb29e',
                externalId: undefined,
                name: 'Hotel(s)',
                required: false,
                type: 'modular_content'
            },

            /**
             * Images (asset)
             */
            images: {
                codename: 'images',
                id: '37720700-dc2e-4070-a64d-d15b2c296f12',
                externalId: undefined,
                name: 'Images',
                required: false,
                type: 'asset'
            },

            /**
             * Included Excursions (modular_content)
             */
            included_excursions: {
                codename: 'included_excursions',
                id: '787ed248-53e8-4d0f-9f2d-1d02cfd7cd10',
                externalId: undefined,
                name: 'Included Excursions',
                required: false,
                type: 'modular_content'
            },

            /**
             * Optional Excursion s  (modular_content)
             */
            optional_excursion_s_: {
                codename: 'optional_excursion_s_',
                id: 'a21d8782-931a-4305-a104-f4a9a9d6c5a5',
                externalId: undefined,
                name: 'Optional Excursion(s)',
                required: false,
                type: 'modular_content'
            },

            /**
             * Reader offer intro 2 (rich_text)
             */
            reader_offer_intro_2: {
                codename: 'reader_offer_intro_2',
                id: '848905b4-2630-41d3-9a76-d13de12e3520',
                externalId: undefined,
                name: 'Reader offer intro 2',
                required: true,
                type: 'rich_text'
            },

            /**
             * Reader offer intro 3 (rich_text)
             */
            reader_offer_intro_3: {
                codename: 'reader_offer_intro_3',
                id: 'd9d28a30-2607-46fa-aaad-ab30cf09e667',
                externalId: undefined,
                name: 'Reader offer intro 3',
                required: true,
                type: 'rich_text'
            },

            /**
             * Tour duration in days (number)
             */
            tour_duration_in_days: {
                codename: 'tour_duration_in_days',
                id: '75d9d13f-0103-46ac-b644-bb044bcc57f6',
                externalId: undefined,
                name: 'Tour duration in days',
                required: true,
                type: 'number'
            },

            /**
             * Tour Intro (rich_text)
             */
            tour_intro: {
                codename: 'tour_intro',
                id: '6623fbb4-aec7-4cd6-88a6-bcbee95b151e',
                externalId: undefined,
                name: 'Tour Intro',
                required: true,
                type: 'rich_text'
            },

            /**
             * Tour Title (text)
             */
            tour_title: {
                codename: 'tour_title',
                id: '876d8a43-5c12-4c3a-a09d-79b0487862ee',
                externalId: undefined,
                name: 'Tour Title',
                required: true,
                type: 'text'
            },

            /**
             * Tour Type (taxonomy)
             */
            tour_type: {
                codename: 'tour_type',
                id: 'e635898b-8de9-40f5-bfe1-6f98e2169b94',
                externalId: undefined,
                name: 'Tour Type',
                required: true,
                type: 'taxonomy'
            },

            /**
             * What s Included (rich_text)
             */
            whats_included: {
                codename: 'whats_included',
                id: 'a1a40563-6186-4f52-834b-e09a0344ef51',
                externalId: undefined,
                name: "What's Included",
                required: true,
                type: 'rich_text'
            }
        }
    },

    /**
     * Tour  No RO Needed
     */
    tour__copy_: {
        codename: 'tour__copy_',
        id: 'b351ceee-fdea-450a-99a5-dd4b53732c4f',
        externalId: undefined,
        name: 'Tour (No RO Needed)',
        elements: {
            /**
             * Export Tour (custom)
             */
            export_tour: {
                codename: 'export_tour',
                id: '8aa22cd0-bec0-4674-9d7f-83826d9fe4d8',
                externalId: undefined,
                name: 'Export Tour',
                required: false,
                type: 'custom'
            },

            /**
             * Hotel s  (modular_content)
             */
            hotel_s_: {
                codename: 'hotel_s_',
                id: 'e23120c8-9310-4bfd-8f10-bcdbe3013d6e',
                externalId: undefined,
                name: 'Hotel(s)',
                required: false,
                type: 'modular_content'
            },

            /**
             * Images (asset)
             */
            images: {
                codename: 'images',
                id: '228a663c-e4c0-45a1-bf49-4338c3cdda40',
                externalId: undefined,
                name: 'Images',
                required: false,
                type: 'asset'
            },

            /**
             * Included Excursions (modular_content)
             */
            included_excursions: {
                codename: 'included_excursions',
                id: 'd5c75130-a886-44f9-950b-dff2c23ad2ff',
                externalId: undefined,
                name: 'Included Excursions',
                required: false,
                type: 'modular_content'
            },

            /**
             * Optional Excursion s  (modular_content)
             */
            optional_excursion_s_: {
                codename: 'optional_excursion_s_',
                id: '4c43fc0d-3a5e-4d82-8115-bb298a65c9c9',
                externalId: undefined,
                name: 'Optional Excursion(s)',
                required: false,
                type: 'modular_content'
            },

            /**
             * Reader offer intro 2 (rich_text)
             */
            reader_offer_intro_2: {
                codename: 'reader_offer_intro_2',
                id: '33f86b39-82d2-460d-bbd4-4f53f400381d',
                externalId: undefined,
                name: 'Reader offer intro 2',
                required: false,
                type: 'rich_text'
            },

            /**
             * Reader offer intro 3 (rich_text)
             */
            reader_offer_intro_3: {
                codename: 'reader_offer_intro_3',
                id: '9c28938d-bdfa-4daa-b45f-b961b30516a5',
                externalId: undefined,
                name: 'Reader offer intro 3',
                required: false,
                type: 'rich_text'
            },

            /**
             * Tour duration in days (number)
             */
            tour_duration_in_days: {
                codename: 'tour_duration_in_days',
                id: '3daa20b1-7384-4b4e-9198-d5b78063bc23',
                externalId: undefined,
                name: 'Tour duration in days',
                required: true,
                type: 'number'
            },

            /**
             * Tour Intro (rich_text)
             */
            tour_intro: {
                codename: 'tour_intro',
                id: '889a6a81-7f1d-4780-82d5-7f435d97fd85',
                externalId: undefined,
                name: 'Tour Intro',
                required: true,
                type: 'rich_text'
            },

            /**
             * Tour Title (text)
             */
            tour_title: {
                codename: 'tour_title',
                id: 'bf99fa38-7936-4173-8484-a776575f446e',
                externalId: undefined,
                name: 'Tour Title',
                required: true,
                type: 'text'
            },

            /**
             * Tour Type (taxonomy)
             */
            tour_type: {
                codename: 'tour_type',
                id: 'c9fe632c-bfdb-4471-8d02-d14c1f26432d',
                externalId: undefined,
                name: 'Tour Type',
                required: true,
                type: 'taxonomy'
            },

            /**
             * What s Included (rich_text)
             */
            untitled_rich_text: {
                codename: 'untitled_rich_text',
                id: '2602cf3f-b91b-4380-84ab-196e8ba8de6d',
                externalId: undefined,
                name: "What's Included",
                required: true,
                type: 'rich_text'
            }
        }
    },

    /**
     * Web spotlight root
     */
    web_spotlight_root: {
        codename: 'web_spotlight_root',
        id: 'e9a559db-bf98-479a-8472-b720c178fbaf',
        externalId: undefined,
        name: 'Web spotlight root',
        elements: {
            /**
             * Content (modular_content)
             */
            content: {
                codename: 'content',
                id: '54ba35ec-9f44-45c4-a8f5-fdf9a3944c26',
                externalId: undefined,
                name: 'Content',
                required: false,
                type: 'modular_content'
            },

            /**
             * Subpages (subpages)
             */
            subpages: {
                codename: 'subpages',
                id: 'd6939665-1984-44f1-88ae-c45489114190',
                externalId: undefined,
                name: 'Subpages',
                required: false,
                type: 'subpages'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'f38fcf08-05b0-42fc-af1b-791103d5155c',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    }
} as const;
