/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const taxonomies = {
    /**
     * Copy Type
     */
    specialist_wording: {
        codename: 'specialist_wording',
        id: '11adcc79-b042-4de5-9529-4b0e711c7b28',
        externalId: undefined,
        name: 'Copy Type',
        terms: {
            blog: {
                codename: 'blog',
                id: '9dd6ff6b-b672-4a04-a0ee-2a9970de3c87',
                externalId: undefined,
                name: 'Blog',
                terms: {}
            },
            brochure_pages: {
                codename: 'brochure_pages',
                id: 'dfd0e05c-b8d6-48bf-88c4-26c671f11dd4',
                externalId: undefined,
                name: 'Brochure Pages',
                terms: {}
            },
            caveat: {
                codename: 'caveat',
                id: 'c3cbee6c-0c0b-481f-9c2c-02029e46feb9',
                externalId: undefined,
                name: 'Caveat',
                terms: {}
            },
            editorial: {
                codename: 'editorial',
                id: '48f3c5a5-18d8-46ef-9dcd-bb612e639605',
                externalId: undefined,
                name: 'Editorial',
                terms: {}
            },
            intro: {
                codename: 'intro',
                id: '94c5e718-ceb3-4f9b-aeac-4f4a16d6b064',
                externalId: undefined,
                name: 'Intro',
                terms: {}
            },
            letter: {
                codename: 'letter',
                id: '0a2a8ba0-8ae4-496a-9714-5387b1adf4d4',
                externalId: undefined,
                name: 'Letter',
                terms: {}
            },
            section_intros: {
                codename: 'section_intros',
                id: 'a88e8096-c62d-40a7-9fed-edfe2f393779',
                externalId: undefined,
                name: 'Section Intros',
                terms: {}
            },
            small_print: {
                codename: 'small_print',
                id: '0a051958-a43b-4bd4-aac2-62c65d1697d6',
                externalId: undefined,
                name: 'Small Print',
                terms: {}
            }
        }
    },

    /**
     * Image Database
     */
    image_database: {
        codename: 'image_database',
        id: '1064fcc6-eb71-4d6a-8df2-f2b903b332fa',
        externalId: undefined,
        name: 'Image Database',
        terms: {
            a_rosa: {
                codename: 'a_rosa',
                id: '6a5a369c-253f-4499-85ad-4d06a92675b4',
                externalId: undefined,
                name: 'A-ROSA',
                terms: {}
            },
            andorra: {
                codename: 'andorra',
                id: '005a6ba6-0af2-4c04-bdc3-29d9bf4f471c',
                externalId: undefined,
                name: 'Andorra',
                terms: {}
            },
            astronomy: {
                codename: 'astronomy',
                id: 'e39e7738-dbac-4dc8-96ac-4b95231b5452',
                externalId: undefined,
                name: 'Astronomy',
                terms: {}
            },
            austria: {
                codename: 'austria',
                id: '8936c8c0-e552-4ca4-b08e-01a22d6e3b2f',
                externalId: undefined,
                name: 'Austria',
                terms: {}
            },
            belgium: {
                codename: 'belgium',
                id: 'ecb46eb8-7591-4ec6-ba8e-7fc9c218bd76',
                externalId: undefined,
                name: 'Belgium',
                terms: {}
            },
            bernina_and_glacier_express: {
                codename: 'bernina_and_glacier_express',
                id: '1623c0e8-9549-4115-ad65-b3a9bc70ea01',
                externalId: undefined,
                name: 'Bernina and Glacier Express',
                terms: {}
            },
            channel_islands: {
                codename: 'channel_islands',
                id: '0a3e4409-2aa7-4457-a818-96510f3bfc73',
                externalId: undefined,
                name: 'Channel Islands',
                terms: {}
            },
            christmas: {
                codename: 'christmas',
                id: '16f2b1d5-9269-4659-9d40-8ae0c97962d2',
                externalId: undefined,
                name: 'Christmas',
                terms: {}
            },
            christmas_markets: {
                codename: 'christmas_markets',
                id: '7b44d966-2cab-4712-b376-44f6ed90978f',
                externalId: undefined,
                name: 'Christmas Markets',
                terms: {}
            },
            coach_images: {
                codename: 'coach_images',
                id: 'c48a65a6-e070-47c5-acd5-d6b8de5bcdad',
                externalId: undefined,
                name: 'Coach Images',
                terms: {}
            },
            concerts: {
                codename: 'concerts',
                id: '0b01de53-12f5-48ec-9ce4-a3c87d6ed019',
                externalId: undefined,
                name: 'Concerts',
                terms: {}
            },
            copyright: {
                codename: 'copyright',
                id: 'c1277c53-8741-428a-8ff7-16d2bc01d7c8',
                externalId: undefined,
                name: 'Copyright',
                terms: {}
            },
            croatia: {
                codename: 'croatia',
                id: '53d35e87-f200-4c1b-8c64-4f736f886bfd',
                externalId: undefined,
                name: 'Croatia',
                terms: {}
            },
            cruise: {
                codename: 'cruise',
                id: 'e5162a2a-0062-4e52-a4ac-046fb8bfa68d',
                externalId: undefined,
                name: 'Cruise',
                terms: {}
            },
            a_rosa_deck_plans: {
                codename: 'a_rosa_deck_plans',
                id: '6a3aea66-64cc-4024-a9cb-274fd5e1269d',
                externalId: undefined,
                name: 'Cruise Ship Deck Plans',
                terms: {}
            },
            cruise_ships: {
                codename: 'cruise_ships',
                id: '1a6d4eb0-ada2-406f-aff7-c38ee5a70a84',
                externalId: undefined,
                name: 'Cruise Ships',
                terms: {}
            },
            cyprus: {
                codename: 'cyprus',
                id: 'e7974719-a169-41b9-96b5-dc6ee1596e9c',
                externalId: undefined,
                name: 'Cyprus',
                terms: {}
            },
            czech_republic: {
                codename: 'czech_republic',
                id: '108a2d58-115c-428a-b000-1ef7bd887106',
                externalId: undefined,
                name: 'Czech Republic',
                terms: {}
            },
            d_day: {
                codename: 'd_day',
                id: 'c4f57cba-d48b-4219-b7e5-ef58f4a01b06',
                externalId: undefined,
                name: 'D-Day',
                terms: {}
            },
            danube_classics: {
                codename: 'danube_classics',
                id: 'ea3f3b8f-641a-4eb2-957d-cf8486ae3787',
                externalId: undefined,
                name: 'Danube Classics',
                terms: {}
            },
            danube_delta: {
                codename: 'danube_delta',
                id: 'd1aa1088-ff89-40b0-9f9f-de62449729a3',
                externalId: undefined,
                name: 'Danube Delta',
                terms: {}
            },
            douro: {
                codename: 'douro',
                id: 'c5cbfc56-a6ad-458b-af86-40354dbb439b',
                externalId: undefined,
                name: 'Douro',
                terms: {}
            },
            europe: {
                codename: 'europe',
                id: '9d1acc14-3d36-4743-9d0d-24d321425b51',
                externalId: undefined,
                name: 'Europe',
                terms: {}
            },
            events: {
                codename: 'events',
                id: '9926a262-019e-43c1-a6cc-501428ba0af6',
                externalId: undefined,
                name: 'Events',
                terms: {}
            },
            events___eu: {
                codename: 'events___eu',
                id: '2f7bc276-6f68-4bbf-b251-36d840b036eb',
                externalId: undefined,
                name: 'Events - EU',
                terms: {}
            },
            events___london: {
                codename: 'events___london',
                id: 'f01aceec-b57a-4e70-b2f8-9fab4fb2ce36',
                externalId: undefined,
                name: 'Events - London',
                terms: {}
            },
            excursions: {
                codename: 'excursions',
                id: 'ae4cee09-bb21-4c26-94e6-7ba1b17ea62e',
                externalId: undefined,
                name: 'Excursions',
                terms: {}
            },
            festive: {
                codename: 'festive',
                id: '78c44857-0481-4d7e-826a-d8a7cff0e660',
                externalId: undefined,
                name: 'Festive',
                terms: {}
            },
            flower_shows: {
                codename: 'flower_shows',
                id: '99abe97b-3b69-4ace-ac70-13a3182bdd69',
                externalId: undefined,
                name: 'Flower Shows',
                terms: {}
            },
            france: {
                codename: 'france',
                id: '9a0fbc63-8c11-4546-a2da-068340a8474f',
                externalId: undefined,
                name: 'France',
                terms: {}
            },
            germany: {
                codename: 'germany',
                id: '00c1b4a0-fbd7-4d48-a7a5-3bbb8a8ea82d',
                externalId: undefined,
                name: 'Germany',
                terms: {}
            },
            heritage_images: {
                codename: 'heritage_images',
                id: 'ac345472-cff3-458a-9bdd-b3e760294090',
                externalId: undefined,
                name: 'Heritage Images',
                terms: {}
            },
            hotels___eu: {
                codename: 'hotels___eu',
                id: 'ae25ed89-b836-461d-83d9-84e1399c60d0',
                externalId: undefined,
                name: 'Hotels - EU',
                terms: {}
            },
            hotels___uk: {
                codename: 'hotels___uk',
                id: '56239345-7e3b-45af-ad34-a0fe8375af46',
                externalId: undefined,
                name: 'Hotels - UK',
                terms: {}
            },
            hungary: {
                codename: 'hungary',
                id: '9086cc5c-d75d-4c83-a771-e325bc924f1e',
                externalId: undefined,
                name: 'Hungary',
                terms: {}
            },
            iceland: {
                codename: 'iceland',
                id: 'fefab213-944a-422d-9c86-96a2b8af1539',
                externalId: undefined,
                name: 'Iceland',
                terms: {}
            },
            ireland: {
                codename: 'ireland',
                id: '6ee97710-9096-4fa6-96d2-64945beeaaa4',
                externalId: undefined,
                name: 'Ireland',
                terms: {}
            },
            isle_of_man: {
                codename: 'isle_of_man',
                id: 'cf689ce7-9aef-43e5-9107-e8f5d87dd14f',
                externalId: undefined,
                name: 'Isle of Man',
                terms: {}
            },
            italy: {
                codename: 'italy',
                id: '6bc7f817-6e1d-4ecf-ba24-9e2d0153f10a',
                externalId: undefined,
                name: 'Italy',
                terms: {}
            },
            lake_constance: {
                codename: 'lake_constance',
                id: '5ff36df0-dc3a-4d70-870b-ff9c396b0862',
                externalId: undefined,
                name: 'Lake Constance',
                terms: {}
            },
            malta: {
                codename: 'malta',
                id: '23835abf-a60d-456e-99de-e86f0c386df9',
                externalId: undefined,
                name: 'Malta',
                terms: {}
            },
            medes_islands: {
                codename: 'medes_islands',
                id: '0892abf6-9b02-4413-8fb3-dac70ae62543',
                externalId: undefined,
                name: 'Medes Islands',
                terms: {}
            },
            monaco: {
                codename: 'monaco',
                id: '6a9c9083-c7a5-4ede-b398-eeac6e3ec3c3',
                externalId: undefined,
                name: 'Monaco',
                terms: {}
            },
            monte_carlo: {
                codename: 'monte_carlo',
                id: '9b0ce6bf-d0a8-45d3-b860-258fa3e9b651',
                externalId: undefined,
                name: 'Monte Carlo',
                terms: {}
            },
            montserrat: {
                codename: 'montserrat',
                id: '615d6a7c-154c-4267-97aa-cf56a602f49c',
                externalId: undefined,
                name: 'Montserrat',
                terms: {}
            },
            moselle: {
                codename: 'moselle',
                id: '4383d153-20e8-4b44-8a06-b433893a8959',
                externalId: undefined,
                name: 'Moselle',
                terms: {}
            },
            netherlands: {
                codename: 'netherlands',
                id: 'f3dc58e1-3d55-41c1-88da-d729ce3ceaad',
                externalId: undefined,
                name: 'Netherlands',
                terms: {}
            },
            normandy: {
                codename: 'normandy',
                id: '10de3f15-a7d4-4d20-a565-d3649a9668fa',
                externalId: undefined,
                name: 'Normandy',
                terms: {}
            },
            northern_lights: {
                codename: 'northern_lights',
                id: 'a9c759f6-71a2-4f18-a548-1696e8a29795',
                externalId: undefined,
                name: 'Northern Lights',
                terms: {}
            },
            poland: {
                codename: 'poland',
                id: '7d9f84eb-db97-4116-9876-3371f44e0db7',
                externalId: undefined,
                name: 'Poland',
                terms: {}
            },
            portugal: {
                codename: 'portugal',
                id: 'cb96f290-43d3-4917-b833-d30963a7f97a',
                externalId: undefined,
                name: 'Portugal',
                terms: {}
            },
            pyrenees: {
                codename: 'pyrenees',
                id: '3f84d8d3-27b7-45ea-bccd-19943f678c38',
                externalId: undefined,
                name: 'Pyrenees',
                terms: {}
            },
            railway: {
                codename: 'railway',
                id: 'fb4d0fd1-9397-45f8-aa22-1db1f75ada2d',
                externalId: undefined,
                name: 'Railway',
                terms: {}
            },
            rhine: {
                codename: 'rhine',
                id: 'f88392c1-26ea-465e-8114-4df65e394b70',
                externalId: undefined,
                name: 'Rhine',
                terms: {}
            },
            rhone: {
                codename: 'rhone',
                id: 'a17e2f83-f3be-4e39-99e0-69983f3a8ee6',
                externalId: undefined,
                name: 'Rhone',
                terms: {}
            },
            royals: {
                codename: 'royals',
                id: '44f2e5d8-efde-4a3e-abd4-92b89f347ce1',
                externalId: undefined,
                name: 'Royals',
                terms: {}
            },
            scandinavia: {
                codename: 'scandinavia',
                id: '41762364-25dd-4cb0-9b6b-8521b7c30f4b',
                externalId: undefined,
                name: 'Scandinavia',
                terms: {}
            },
            scotland: {
                codename: 'scotland',
                id: 'b5d48ddc-107c-4ce3-9d05-ac17d01370f1',
                externalId: undefined,
                name: 'Scotland',
                terms: {}
            },
            seine: {
                codename: 'seine',
                id: '4127ae61-c0cc-4718-a297-a188c18735c5',
                externalId: undefined,
                name: 'Seine',
                terms: {}
            },
            slovakia: {
                codename: 'slovakia',
                id: '3a8c572c-1df3-4cbd-baa4-914b3a142aef',
                externalId: undefined,
                name: 'Slovakia',
                terms: {}
            },
            spain: {
                codename: 'spain',
                id: 'df25d1cc-8210-4cc1-bb3b-db5615a4fbc9',
                externalId: undefined,
                name: 'Spain',
                terms: {}
            },
            sri_lanka: {
                codename: 'sri_lanka',
                id: '59a33259-41ad-4657-ae4e-3331e3c347c2',
                externalId: undefined,
                name: 'Sri Lanka',
                terms: {}
            },
            staff_photos: {
                codename: 'staff_photos',
                id: '8d3c49d5-3128-4146-a693-f613596253f7',
                externalId: undefined,
                name: 'Staff Photos',
                terms: {}
            },
            switzerland: {
                codename: 'switzerland',
                id: 'd300d117-2243-4977-b08e-89c0ab7697e8',
                externalId: undefined,
                name: 'Switzerland',
                terms: {}
            },
            theatre: {
                codename: 'theatre',
                id: '049a78c0-42bc-4d9c-8090-bcd8cdefe7ad',
                externalId: undefined,
                name: 'Theatre',
                terms: {}
            },
            valley_of_de_bocq_train: {
                codename: 'valley_of_de_bocq_train',
                id: '3c00a6f0-59ca-4127-b0cd-e1535951038b',
                externalId: undefined,
                name: 'Valley of de Bocq Train',
                terms: {}
            },
            wales: {
                codename: 'wales',
                id: 'f469f7b7-69ce-458a-b78f-20cd625d99e2',
                externalId: undefined,
                name: 'Wales',
                terms: {}
            },
            warner: {
                codename: 'warner',
                id: 'a179bef0-fcb2-437f-b8c7-271efeae64e0',
                externalId: undefined,
                name: 'Warner',
                terms: {}
            }
        }
    },

    /**
     * Tour Type
     */
    tour_type: {
        codename: 'tour_type',
        id: '6f59296a-e360-4799-9d69-df6c577ec9f3',
        externalId: undefined,
        name: 'Tour Type',
        terms: {
            astro: {
                codename: 'astro',
                id: '6ec7662e-23ff-4165-a4f6-26b64a37668f',
                externalId: undefined,
                name: 'Astro',
                terms: {}
            },
            channel_islands: {
                codename: 'channel_islands',
                id: 'd02b22cd-87da-4bb2-8540-5f8d39832716',
                externalId: undefined,
                name: 'Channel Islands',
                terms: {}
            },
            classic: {
                codename: 'classic',
                id: 'baf72991-2858-4cf8-b2af-36db9928a2cf',
                externalId: undefined,
                name: 'Classic',
                terms: {}
            },
            cruise: {
                codename: 'cruise',
                id: '3e4dcfac-cc65-44de-b6ef-cab4ebe00412',
                externalId: undefined,
                name: 'Cruise',
                terms: {}
            },
            eu: {
                codename: 'eu',
                id: 'aed16f66-db22-43bf-8ada-ce681f0cc062',
                externalId: undefined,
                name: 'EU',
                terms: {}
            },
            events: {
                codename: 'events',
                id: 'a9c809e1-e73b-4d30-9ac5-a17768844c9a',
                externalId: undefined,
                name: 'Events',
                terms: {}
            },
            family_fun: {
                codename: 'family_fun',
                id: '1bda657b-0dd9-4b41-9fe4-d99c17aa0e96',
                externalId: undefined,
                name: 'Family Fun',
                terms: {}
            },
            festive: {
                codename: 'festive',
                id: '89fe169f-f96c-4742-9940-a31f3fa5afa1',
                externalId: undefined,
                name: 'Festive',
                terms: {}
            },
            heritage: {
                codename: 'heritage',
                id: 'b196e3f1-cfae-4276-a0f0-828e9a459959',
                externalId: undefined,
                name: 'Heritage',
                terms: {}
            },
            inbound: {
                codename: 'inbound',
                id: 'ed234b43-4655-45e4-b1fa-fef74c05724b',
                externalId: undefined,
                name: 'Inbound',
                terms: {}
            },
            ireland: {
                codename: 'ireland',
                id: 'a39bfc4d-7518-4184-b123-83869f0504b5',
                externalId: undefined,
                name: 'Ireland',
                terms: {}
            },
            london: {
                codename: 'london',
                id: '34cbb707-9b53-4be6-a3fd-0d5058bf3cc8',
                externalId: undefined,
                name: 'London',
                terms: {}
            },
            sports: {
                codename: 'sports',
                id: '58d2b72f-aafb-4f8b-852e-66fe644f7053',
                externalId: undefined,
                name: 'Sports',
                terms: {}
            },
            supervalue: {
                codename: 'supervalue',
                id: '4185a0e0-132f-489c-a4df-56b09172000b',
                externalId: undefined,
                name: 'Supervalue',
                terms: {}
            },
            winter_sun: {
                codename: 'winter_sun',
                id: 'd0eca68b-4598-4672-9c1f-32d5d7c8ae28',
                externalId: undefined,
                name: 'Winter Sun',
                terms: {}
            }
        }
    }
} as const;
